name: real-time-web-analytics-app

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
    - MYSQL_DATABASE=$(MYSQL_DATABASE)
    - MYSQL_USER=$(MYSQL_USER)
    - MYSQL_PASSWORD=$(MYSQL_ROOT_PASSWORD)
    ports:
      - "3306:3306"


